In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=read_excel(r"/content/Sample - Superstore.xlsx")
df1.head()

NameError: name 'read_excel' is not defined

In [3]:
import pandas as pd
import numpy as np

df1 = pd.read_excel(r"/content/Sample - Superstore.xlsx")  # Use pd.read_excel() to call the function
df1.head()

,A`,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,4962,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,98103.0,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801
1,4963,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,98103.0,West,OFF-AR-10001427,Office Supplies,Art,Newell 330,17.940,3,0.0,4.6644
2,4964,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,98103.0,West,OFF-ST-10002344,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.940,3,0.0,4.8588
3,8223,CA-2016-152905,2016-02-18,2016-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,76017.0,Central,OFF-ST-10000321,Office Supplies,Storage,Akro Stacking Bins,12.624,2,0.2,-2.5248
4,8802,CA-2018-140935,2018-11-10,2018-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,73120.0,Central,TEC-PH-10000562,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544

In [7]:
df1[df1['Order Id']=='Region']

KeyError: 'Order Id'

In [8]:
df1[df1['Order ID']=='Region']  # Change 'Order Id' to 'Order ID'

Empty DataFrame
Columns: [A`, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [9]:
df2=pd.read_csv(r"/content/fact_bating_summary.csv")
df2.head()

,match_id,match,teamInnings,battingPos,batsmanName,out/not_out,runs,balls,4s,6s,SR
0,T203817,Super Kings Vs KKR,Super Kings,1,RuturajGaikwad,out,32,27,3,1,118.51
1,T203817,Super Kings Vs KKR,Super Kings,2,FafduPlessis,out,86,59,7,3,145.76
2,T203817,Super Kings Vs KKR,Super Kings,3,RobinUthappa,out,31,15,0,3,206.66
3,T203817,Super Kings Vs KKR,Super Kings,4,MoeenAli,not_out,37,20,2,3,185.00
4,T203817,Super Kings Vs KKR,KKR,1,ShubmanGill,out,51,43,6,0,118.60

In [10]:
df2.columns

Index(['match_id', 'match', 'teamInnings', 'battingPos', 'batsmanName',
       'out/not_out', 'runs', 'balls', '4s', '6s', 'SR'],
      dtype='object')

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3268 entries, 0 to 3267
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   match_id     3268 non-null   object
 1   match        3268 non-null   object
 2   teamInnings  3268 non-null   object
 3   battingPos   3268 non-null   int64
 4   batsmanName  3268 non-null   object
 5   out/not_out  3268 non-null   object
 6   runs         3268 non-null   int64
 7   balls        3268 non-null   int64
 8   4s           3268 non-null   int64
 9   6s           3268 non-null   int64
 10  SR           3268 non-null   object
dtypes: int64(5), object(6)
memory usage: 281.0+ KB

In [13]:
df2.describe()

        battingPos         runs        balls           4s           6s
count  3268.000000  3268.000000  3268.000000  3268.000000  3268.000000
mean      4.772032    19.820073    14.700734     1.744798     0.875459
std       2.714852    21.885699    13.516978     2.329142     1.426316
min       1.000000     0.000000     0.000000     0.000000     0.000000
25%       2.000000     3.000000     4.000000     0.000000     0.000000
50%       4.000000    12.000000    10.000000     1.000000     0.000000
75%       7.000000    29.000000    21.000000     3.000000     1.000000
max      11.000000   140.000000    70.000000    16.000000    10.000000

In [14]:
df2.tail(1)

,match_id,match,teamInnings,battingPos,batsmanName,out/not_out,runs,balls,4s,6s,SR
3267,T201566,Super Kings Vs Titans,Titans,7,RashidKhan,not_out,10,3,1,1,333.33

In [15]:
df2.head(10)

,match_id,match,teamInnings,battingPos,batsmanName,out/not_out,runs,balls,4s,6s,SR
0,T203817,Super Kings Vs KKR,Super Kings,1,RuturajGaikwad,out,32,27,3,1,118.51
1,T203817,Super Kings Vs KKR,Super Kings,2,FafduPlessis,out,86,59,7,3,145.76
2,T203817,Super Kings Vs KKR,Super Kings,3,RobinUthappa,out,31,15,0,3,206.66
3,T203817,Super Kings Vs KKR,Super Kings,4,MoeenAli,not_out,37,20,2,3,185.00
4,T203817,Super Kings Vs KKR,KKR,1,ShubmanGill,out,51,43,6,0,118.60
5,T203817,Super Kings Vs KKR,KKR,2,VenkateshIyer,out,50,32,5,3,156.25
6,T203817,Super Kings Vs KKR,KKR,3,NitishRana,out,0,1,0,0,0.00
7,T203817,Super Kings Vs KKR,KKR,4,SunilNarine,out,2,2,0,0,100.00
8,T203817,Super Kings Vs KKR,KKR,5,EoinMorgan,out,4,8,0,0,50.00
9,T203817,Super Kings Vs KKR,KKR,6,DineshKarthik,out,9,7,0,1,128.57

In [16]:
df2.balls

0       27
1       59
2       15
3       20
4       43
        ..
3263    17
3264    11
3265    21
3266    14
3267     3
Name: balls, Length: 3268, dtype: int64

In [17]:
df2['balls']

0       27
1       59
2       15
3       20
4       43
        ..
3263    17
3264    11
3265    21
3266    14
3267     3
Name: balls, Length: 3268, dtype: int64

In [18]:
df2.balls.min()

0

In [19]:
df2.balls.max()

70

In [21]:
df2['6s'].mean()

0.8754589963280294

In [23]:
df2[df2['batsmanName']=='FafduPlessis']

,match_id,match,teamInnings,battingPos,batsmanName,out/not_out,runs,balls,4s,6s,SR
1,T203817,Super Kings Vs KKR,Super Kings,2,FafduPlessis,out,86,59,7,3,145.76
56,T201819,Capitals Vs Super Kings,Super Kings,2,FafduPlessis,out,1,2,0,0,50.00
113,T201866,Super Kings Vs Punjab Kings,Super Kings,2,FafduPlessis,out,76,55,8,2,138.18
158,T207682,Super Kings Vs Capitals,Super Kings,2,FafduPlessis,out,10,8,2,0,125.00
207,T205672,Super Kings Vs Royals,Super Kings,2,FafduPlessis,out,25,19,2,1,131.57
260,T203061,Sunrisers Vs Super Kings,Super Kings,2,FafduPlessis,out,41,36,3,2,113.88
353,T202406,KKR Vs Super Kings,Super Kings,2,FafduPlessis,out,43,30,7,0,143.33
404,T207776,RCB Vs Super Kings,Super Kings,2,FafduPlessis,out,31,26,2,2,119.23
468,T201256,Super Kings Vs Mumbai,Super Kings,2,FafduPlessis,out,0,3,0,0,0.00
515,T203694,Super Kings Vs Mumbai,Super Kings,2,FafduPlessis,out,50,28,2,4,178.57
575,T205094,Sunrisers Vs Super Kings,Super Kings,2,FafduPlessis,out,56,38,6,1,147.36
611,T202915,Super Kings Vs RCB,Super Kings,2,FafduPlessis,out,50,41,5,1,121.95
668,T202233,Super Kings Vs KKR,Super Kings,2,FafduPlessis,not_out,95,60,9,4,158.33
715,T209089,Super Kings Vs Royals,Super Kings,2,FafduPlessis,out,33,17,4,2,194.11
793,T205292,Punjab Kings Vs Super Kings,Super Kings,2,FafduPlessis,not_out,36,33,3,1,109.09
887,T206363,Super Kings Vs Capitals,Super Kings,2,FafduPlessis,out,0,3,0,0,0.00
935,T201109,RCB Vs Royals,RCB,2,FafduPlessis,out,25,27,3,0,92.59
950,T207136,RCB Vs Super Giants,RCB,2,FafduPlessis,out,0,1,0,0,0.00
1032,T201867,Titans Vs RCB,RCB,2,FafduPlessis,out,44,38,5,0,115.78
1141,T203332,Punjab Kings Vs RCB,RCB,2,FafduPlessis,out,10,8,2,0,125.00
1240,T207464,RCB Vs Sunrisers,RCB,2,FafduPlessis,not_out,73,50,8,2,146.00
1318,T207511,RCB Vs Super Kings,RCB,2,FafduPlessis,out,38,22,4,1,172.72
1405,T208841,RCB Vs Titans,RCB,2,FafduPlessis,out,0,4,0,0,0.00
1482,T205212,Royals Vs RCB,RCB,2,FafduPlessis,out,23,21,3,1,109.52
1523,T208774,RCB Vs Sunrisers,RCB,1,FafduPlessis,out,5,7,1,0,71.42
1603,T204535,RCB Vs Super Giants,RCB,2,FafduPlessis,out,96,64,11,2,150.00
1669,T205793,RCB Vs Capitals,RCB,1,FafduPlessis,out,8,11,2,0,72.72
1757,T203601,Super Kings Vs RCB,RCB,1,FafduPlessis,out,8,9,0,0,88.88
1825,T204746,Mumbai Vs RCB,RCB,1,FafduPlessis,out,16,24,1,0,66.66
1889,T203456,Royals Vs RCB,RCB,1,FafduPlessis,out,29,20,5,0,145.00
2016,T203578,KKR Vs RCB,RCB,1,FafduPlessis,out,5,4,1,0,125.00
2056,T208141,RCB Vs Punjab Kings,RCB,1,FafduPlessis,out,88,57,3,7,154.38
2163,T201605,RCB Vs Titans,RCB,2,FafduPlessis,out,28,19,5,0,147.36
2243,T202467,Sunrisers Vs RCB,RCB,2,FafduPlessis,out,71,47,7,2,151.06
2309,T204453,RCB Vs Royals,RCB,2,FafduPlessis,out,55,44,3,2,125.00
2408,T205430,RCB Vs Mumbai,RCB,2,FafduPlessis,out,65,41,5,3,158.53
2463,T208517,RCB Vs Capitals,RCB,2,FafduPlessis,out,45,32,5,1,140.62
2554,T203494,RCB Vs Super Giants,RCB,2,FafduPlessis,out,44,40,1,1,110.00
2673,T202291,KKR Vs RCB,RCB,2,FafduPlessis,out,17,7,1,2,242.85
2737,T205220,RCB Vs Royals,RCB,2,FafduPlessis,out,62,39,8,2,158.97
2821,T209410,RCB Vs Punjab Kings,RCB,2,FafduPlessis,out,84,56,5,5,150.00
2879,T206232,Super Kings Vs RCB,RCB,2,FafduPlessis,out,62,33,5,4,187.87
2941,T208157,RCB Vs Capitals,RCB,2,FafduPlessis,out,22,16,3,1,137.50
3024,T202162,RCB Vs Super Giants,RCB,2,FafduPlessis,not_out,79,46,5,5,171.73
3127,T207668,KKR Vs RCB,RCB,2,FafduPlessis,out,23,12,2,2,191.66
3197,T202485,Mumbai Vs RCB,RCB,2,FafduPlessis,out,73,43,5,6,169.76

In [25]:
df2[['teamInnings','match']]

      teamInnings                  match
0     Super Kings     Super Kings Vs KKR
1     Super Kings     Super Kings Vs KKR
2     Super Kings     Super Kings Vs KKR
3     Super Kings     Super Kings Vs KKR
4             KKR     Super Kings Vs KKR
...           ...                    ...
3263       Titans  Super Kings Vs Titans
3264       Titans  Super Kings Vs Titans
3265       Titans  Super Kings Vs Titans
3266       Titans  Super Kings Vs Titans
3267       Titans  Super Kings Vs Titans

[3268 rows x 2 columns]

In [38]:
df2[['batsmanName','runs','teamInnings']][df2['6s']>=6]

          batsmanName  runs   teamInnings
120           KLRahul    98  Punjab Kings
499        JosButtler   124        Royals
518      AmbatiRayudu    72   Super Kings
524     KieronPollard    87        Mumbai
666   DevduttPadikkal   101           RCB
...               ...   ...           ...
3032   NicholasPooran    62  Super Giants
3063       RinkuSingh    48           KKR
3197     FafduPlessis    73           RCB
3218       KyleMayers    73  Super Giants
3253   RuturajGaikwad    92   Super Kings

[61 rows x 3 columns]

In [39]:
df2[df2['teamInnings']=='RCB'][['4s','6s','runs']]

      4s  6s  runs
31     2   0    21
32     5   0    39
33     0   0     9
34     1   0    15
35     1   0    11
...   ..  ..   ...
3136   2   1    17
3196   6   5    82
3197   5   6    73
3198   0   0     0
3199   0   2    12

[350 rows x 3 columns]

In [42]:
df2[['teamInnings','batsmanName','runs','balls']][(df2['runs']>60) & (df2['balls']<120)].head(5)

    teamInnings     batsmanName  runs  balls
1   Super Kings    FafduPlessis    86     59
55  Super Kings  RuturajGaikwad    70     50
57  Super Kings    RobinUthappa    63     44
71          RCB    SrikarBharat    78     52
75       Mumbai     IshanKishan    84     32

In [46]:
df2[['teamInnings','batsmanName','runs','balls']][(df2['runs']>60)][df2['teamInnings']=='RCB'].head(10)

<ipython-input-46-074019dbd962>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[['teamInnings','batsmanName','runs','balls']][(df2['runs']>60)][df2['teamInnings']=='RCB'].head(10)

     teamInnings      batsmanName  runs  balls
71           RCB     SrikarBharat    78     52
397          RCB  DevduttPadikkal    70     50
583          RCB     ABdeVilliers    75     42
665          RCB       ViratKohli    72     47
666          RCB  DevduttPadikkal   101     52
751          RCB     GlennMaxwell    78     49
752          RCB     ABdeVilliers    76     34
951          RCB     RajatPatidar   112     54
1031         RCB       ViratKohli    73     54
1240         RCB     FafduPlessis    73     50

In [49]:
df2.groupby('batsmanName')['runs'].sum().nlargest(5)

batsmanName
ShubmanGill       1851
FafduPlessis      1831
RuturajGaikwad    1593
KLRahul           1516
JosButtler        1509
Name: runs, dtype: int64

In [ ]:
df2.groupby('batsmanName')['runs'].sum().nlargest(5)